---
title: "Data exploration"
author: "Mahfuza Haque Mahi"
date: "2026-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(tibble)
library(naniar)
library(lme4)
library(ggplot2)
library(ggbeeswarm)
library(ggpubr)
library(table1)
library(gtsummary) # this is a package to make tables of descriptive stats
library(flextable) # this can help print tables to docx (MS Word)
library(tableone) # this is another fairly easy to use descriptive stats package
library(psych) # used for corr.test
library(knitr) # for writing tables
library(kableExtra) # for writing tables
library(cmdstanr)
library(bayesplot)  # diagnostic plots of the MCMC chains
library(posterior)  # for summarizing posterior draws
library(bayestestR) # for calculating higest density posterior intervals
library(mcmcse)     # for calculating MCMCSE's
library(loo)        # for getting model fit statistics (WAIC and LOO-IC)

raw_dat <- read.csv(here::here("Project1/DataRaw", "hiv_6624_final.csv"))
```


## Initial overview of the dataset

```{r}
# drop the index column
raw_dat <- raw_dat %>% select(-any_of("X"))

# Check structure
str(raw_dat)
head(raw_dat)
nrow(raw_dat) 

summary(raw_dat)
glimpse(raw_dat)
```

## View the Missingness pattern of variables:

```{r}
naniar::gg_miss_var(raw_dat)
naniar::vis_miss(raw_dat)
```
## Structure check
```{r}
# Number of visits per subject
table(table(raw_dat$newid))

# Check min/max years per subject
raw_dat %>%
  group_by(newid) %>%
  summarise(min_year = min(years, na.rm = TRUE),
            max_year = max(years, na.rm = TRUE),
            n_visits = n())

```



## Visual exploration of the outcomes

```{r}
hist(raw_dat$VLOAD); hist(raw_dat$LEU3N); hist(raw_dat$AGG_PHYS); hist(raw_dat$AGG_MENT)
hist(log10(raw_dat$VLOAD)); hist(sqrt(raw_dat$LEU3N)); hist(log(101-raw_dat$AGG_PHYS)); hist(log(101-raw_dat$AGG_MENT))
```


## Iniytial look at the descriptives
```{r}
table(raw_dat$RACE, useNA = "ifany")
table(raw_dat$years)
table(raw_dat$EDUCBAS)
```

```{r}
table1(~ age + hard_drugs + hivpos + ART + everART + VLOAD + LEU3N + AGG_PHYS + AGG_MENT | years, raw_dat)
```